language: node_js
warnings_are_errors: false
node_js:
  - lts/*
before_install:
  - cd client
  - rm -f package-lock.json
  - rm -rf node_modules
  - npm cache clean
  - npm install
script:
   - npm run build
