name: Create Web Release
uses: LamkasDev/zip-release@0.4.1

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Create Web Release
      uses: lamkasdev/zip-release@master
      with:
        directory: 'client'
        filename: 'build.zip'
